apps:
  pages:
    - number: 1
      items:
        - App Store
        - Safari
        - Mail
        - Contacts
        - Calendar
        - Reminders
        - Notes
        - FaceTime
        - Messages
        - Maps
        - Find My
        - Photos
        - Music
        - Podcasts
        - TV
        - GarageBand
        - iMovie
        - Keynote
        - Numbers
        - Pages
        - Clock
        - Calculator
        - Home
        - Siri
        - iPhone Mirroring
        - Passwords
        - System Settings
        - folder: Other
          pages:
            - number: 1
              items:
                - Shortcuts
                - QuickTime Player
                - Dictionary
                - TextEdit
                - Font Book
                - Screen Sharing
                - Mission Control
                - Time Machine
                - Preview
                - Screenshot
                - Image Capture
                - Digital Color Meter
                - ColorSync Utility
                - Stickies
                - Grapher
                - VoiceOver Utility
                - Print Center
                - Automator
                - Script Editor
                - Audio MIDI Setup
                - Bluetooth File Exchange
                - Disk Utility
                - System Information
                - Activity Monitor
                - Console
                - Terminal
                - AirPort Utility
                - Migration Assistant
                - LogiPluginService
                - Freeform
                - Books
                - Stocks
                - Voice Memos
                - Photo Booth
        - folder: Games
          pages:
            - number: 1
              items:
                - Chess
        - Weather
        - Grammarly Desktop
    - number: 2
      items:
        - Tips
        - Logi Options+
        - Boop
        - iTerm
        - Postman
        - Sourcetree
        - Visual Studio Code
        - Burp Suite Community Edition
        - ZAP
        - Wireshark
        - GPG Keychain
        - VeraCrypt
        - Audacity
        - GIMP
        - Inkscape
        - OBS
        - Shotcut
        - calibre
        - Spotify
        - Transmission
        - VLC
        - 1Password
        - Standard Notes
        - Orion
        - Arc
        - QLMarkdown
        - QuickLook Video
        - AltTab
        - AnyBar
        - Espanso
        - Finicky
        - Hidden Bar
        - Mjolnir
        - Simulator
    - number: 3
      items:
        - OpenInTerminal
        - Raycast
        - Santa
        - Shottr
        - Stats
        - CotEditor
        - Little Snitch
        - Warp
        - Sonos
        - 1Password for Safari
        - Final Cut Pro
        - LanScan
        - Microsoft Excel
        - Microsoft OneNote
        - Microsoft PowerPoint
        - Microsoft Word
        - NordVPN
        - OneDrive
        - Slack
        - Speediness
        - Tailscale
        - Trello
        - Xcode
        - Magnet
        - Spark Desktop
        - Tresorit
        - Microsoft Teams
        - OrbStack
        - Maestral
        - Chromium
        - Claude
widgets:
  pages: []
dock_items:
  apps:
    - /Users/ivarvoorman/Applications/iTerm.app
    - /System/Applications/Launchpad.app
    - /Users/ivarvoorman/Applications/Arc.app
    - /Users/ivarvoorman/Applications/Visual Studio Code.app
    - /Applications/Spark Desktop.app
    - /System/Volumes/Preboot/Cryptexes/App/System/Applications/Safari.app
    - /Users/ivarvoorman/Applications/Warp.app
    - /System/Applications/Maps.app
    - /System/Applications/Photos.app
    - /System/Applications/Calendar.app
    - /System/Applications/Reminders.app
    - /System/Applications/Notes.app
    - /System/Applications/App Store.app
    - /System/Applications/System Settings.app
    - /Users/ivarvoorman/Applications/Sourcetree.app
    - /Users/ivarvoorman/Applications/Spotify.app
    - /Applications/Claude.app
  others:
    - path: ~/Downloads
      view: 1
      sort: 2
  settings:
    autohide: true
    largesize: 56
    magnification: true
    minimize-to-application: true
    mru-spaces: false
    show-recents: false
    tilesize: 41
desktop: {}
