# Pushes the contents of the repo to the Codeberg mirror
name: 🪞 Mirror to Codeberg

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0'  # At 02:00 on Sunday
  push:
    branches:
      - main
      - master

jobs:
  codeberg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Configure Git LFS
        run: |
          git lfs install
          git lfs pull
          git config lfs.allowincompletepush true
          git config lfs.locksverify false

      - name: Configure SSH and known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CODEBERG_SSH }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -t rsa,ecdsa,ed25519 codeberg.org >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          cat >> ~/.ssh/config <<EOF
          Host codeberg.org
            HostName codeberg.org
            User git
            IdentityFile ~/.ssh/id_ed25519
            IdentitiesOnly yes
            StrictHostKeyChecking yes
          EOF

      - name: Mirror to Codeberg
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@codeberg.org:frontman/dotfiles.git
          ssh_private_key: ${{ secrets.CODEBERG_SSH }}

      - name: Push LFS objects
        if: success()
        run: |
          # Disable LFS locks since Codeberg doesn't support them
          git config --global lfs.https://codeberg.org/frontman/dotfiles.git/info/lfs.locksverify false
          
          # Add remote if it doesn't exist
          if ! git remote | grep -q '^codeberg$'; then
            git remote add codeberg git@codeberg.org:frontman/dotfiles.git
          fi
          
          # Push LFS objects with error handling
          git lfs push --all codeberg || {
            echo "Failed to push LFS objects, retrying without locks..."
            git config --global lfs.allowincompletepush true
            git lfs push --all codeberg
          }